# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('oilType', models.CharField(max_length=10)),
                ('carType', models.CharField(max_length=10)),
                ('comment', models.CharField(blank=True, max_length=20, null=True)),
                ('kpl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPay',
            fields=[
                ('extraPayId', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=10)),
                ('overHourDate', models.DateField(blank=True, null=True)),
                ('sumOverHour', models.FloatField(blank=True, null=True)),
                ('compensatedHour', models.FloatField(blank=True, default=0, null=True)),
                ('empSalary', models.IntegerField(default=0)),
                ('compensatedComment', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('payStatus', models.CharField(default='N', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuelId', models.AutoField(primary_key=True, serialize=False)),
                ('fuelMoney', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('comment2', models.CharField(blank=True, max_length=200, null=True)),
                ('fuelStatus', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('oilId', models.AutoField(primary_key=True, serialize=False)),
                ('oilDate', models.DateField()),
                ('oilMoney', models.FloatField()),
                ('mpk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OverHour',
            fields=[
                ('overHourId', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(blank=True, max_length=10, null=True)),
                ('overHourTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('overHourStartDate', models.DateTimeField(blank=True, null=True)),
                ('overHourEndDate', models.DateTimeField(blank=True, null=True)),
                ('overHour', models.FloatField(blank=True, default=0, null=True)),
                ('overHourWeekDay', models.FloatField(blank=True, default=0, null=True)),
                ('overHourCost', models.FloatField(blank=True, default=0, null=True)),
                ('overHourCostWeekDay', models.FloatField(blank=True, default=0, null=True)),
                ('foodCost', models.FloatField(blank=True, default=0, null=True)),
                ('overHourStatus', models.CharField(blank=True, default='Y', max_length=10, null=True)),
            ],
        ),
    ]
