# Generated by Django 2.1.7 on 2019-10-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0003_auto_20190731_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverHour',
            fields=[
                ('overHourId', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=10)),
                ('overHourDate', models.DateField()),
                ('sumOverHour', models.FloatField(blank=True, null=True)),
                ('compensatedHour', models.FloatField(blank=True, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
