# Generated by Django 2.1.7 on 2019-10-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('hr', '0001_initial'),
        ('extrapay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overhour',
            name='empId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='overhour',
            name='extraPayId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extrapay.ExtraPay'),
        ),
        migrations.AddField(
            model_name='overhour',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport'),
        ),
        migrations.AddField(
            model_name='oil',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrapay.Car'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='geolocationId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Geolocation'),
        ),
        migrations.AddField(
            model_name='extrapay',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
    ]
