# Generated by Django 2.1.7 on 2019-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overhour',
            name='payHour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
