# Generated by Django 2.1.7 on 2019-10-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20191014_2245'),
        ('extrapay', '0002_overhour_payhour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('oilType', models.CharField(max_length=10)),
                ('carType', models.CharField(max_length=10)),
                ('comment', models.CharField(blank=True, max_length=20, null=True)),
                ('kpl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuelId', models.AutoField(primary_key=True, serialize=False)),
                ('distance1', models.FloatField(default=0)),
                ('distance2', models.FloatField(default=0)),
                ('distance3', models.FloatField(default=0)),
                ('totalDistance', models.FloatField()),
                ('fuelMoney', models.IntegerField(blank=True, null=True)),
                ('fuelStatus', models.CharField(default='N', max_length=1)),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport')),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('oilId', models.AutoField(primary_key=True, serialize=False)),
                ('oilDate', models.DateField()),
                ('oilMoney', models.FloatField()),
                ('mpk', models.IntegerField()),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrapay.Car')),
            ],
        ),
    ]
