# Generated by Django 2.1.7 on 2020-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0003_extrapay_empsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='comment2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
