# Generated by Django 2.1.7 on 2019-10-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20190731_1350'),
        ('service', '0017_remove_servicereport_overhourid'),
        ('extrapay', '0003_car_fuel_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPay',
            fields=[
                ('extraPayId', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=10)),
                ('overHourDate', models.DateField()),
                ('sumOverHour', models.FloatField(blank=True, null=True)),
                ('compensatedHour', models.FloatField(blank=True, null=True)),
                ('', models.FloatField(blank=True, null=True)),
                ('payStatus', models.CharField(default='N', max_length=10)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.RenameField(
            model_name='overhour',
            old_name='compensatedHour',
            new_name='foodCost',
        ),
        migrations.RenameField(
            model_name='overhour',
            old_name='payHour',
            new_name='overHour',
        ),
        migrations.RenameField(
            model_name='overhour',
            old_name='sumOverHour',
            new_name='overHourCost',
        ),
        migrations.RemoveField(
            model_name='overhour',
            name='overHourDate',
        ),
        migrations.AddField(
            model_name='overhour',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='overhour',
            name='overHourEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overhour',
            name='overHourStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overhour',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport'),
        ),
        migrations.AlterField(
            model_name='overhour',
            name='empId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AlterField(
            model_name='overhour',
            name='empName',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='overhour',
            name='extraPayId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extrapay.ExtraPay'),
        ),
    ]
