# Generated by Django 2.1.7 on 2019-10-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0004_auto_20191015_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapay',
            name='overHourDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
