# Generated by Django 2.1.7 on 2019-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0005_auto_20191015_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overhour',
            name='overHourEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overhour',
            name='overHourStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
