# Generated by Django 2.1.7 on 2019-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0006_auto_20191016_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapay',
            name='compensatedComment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
