# Generated by Django 2.1.7 on 2019-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0007_extrapay_compensatedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='overhour',
            name='overHourCostWeekDay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overhour',
            name='overHourWeekDay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
