# Generated by Django 2.1.7 on 2019-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0008_auto_20191016_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapay',
            name='compensatedComment',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
