# Generated by Django 2.1.7 on 2019-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0009_auto_20191017_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overhour',
            name='comment',
        ),
        migrations.AddField(
            model_name='overhour',
            name='overHourTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
