# Generated by Django 2.1.7 on 2019-10-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0010_auto_20191017_1424'),
        ('extrapay', '0006_fuel_comment'),
    ]

    operations = [
    ]
