# Generated by Django 2.1.7 on 2019-10-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0011_merge_20191017_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='distance1',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='distance2',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='distance3',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='totalDistance',
        ),
    ]
