# Generated by Django 2.1.7 on 2019-10-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0012_auto_20191018_1502'),
        ('extrapay', '0012_auto_20191018_1008'),
    ]

    operations = [
    ]
