# Generated by Django 2.1.7 on 2019-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0013_merge_20191018_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='overhour',
            name='overHourStatus',
            field=models.CharField(blank=True, default='Y', max_length=10, null=True),
        ),
    ]
