# Generated by Django 2.1.7 on 2019-10-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0014_overhour_overhourstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrapay',
            name='',
        ),
    ]
