# Generated by Django 2.1.7 on 2019-10-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_geolocation_tollmoney'),
        ('extrapay', '0015_remove_extrapay_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='serviceId',
        ),
        migrations.AddField(
            model_name='fuel',
            name='geolocationId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Geolocation'),
        ),
    ]
