# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('companyNameKo', models.CharField(max_length=100, unique=True)),
                ('companyNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('ceo', models.CharField(blank=True, max_length=30, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('companyLatitude', models.FloatField(blank=True, null=True)),
                ('companyLongitude', models.FloatField(blank=True, null=True)),
                ('companyDbms', models.TextField(blank=True, null=True)),
                ('companySystem', models.TextField(blank=True, null=True)),
                ('dbComment', models.TextField(blank=True, null=True)),
                ('solutionComment', models.TextField(blank=True, null=True)),
                ('dbContractStartDate', models.DateField(blank=True, null=True)),
                ('dbContractEndDate', models.DateField(blank=True, null=True)),
                ('solutionContractStartDate', models.DateField(blank=True, null=True)),
                ('solutionContractEndDate', models.DateField(blank=True, null=True)),
                ('companyStatus', models.CharField(choices=[('Y', 'Y'), ('N', 'N'), ('X', 'X')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=10)),
                ('customerDeptName', models.CharField(blank=True, max_length=30, null=True)),
                ('customerPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('customerEmail', models.CharField(blank=True, max_length=254, null=True)),
                ('customerType', models.CharField(blank=True, choices=[('솔루션', '솔루션'), ('DB', 'DB'), ('영업', '영업'), ('세금', '세금')], max_length=10, null=True)),
                ('customerStatus', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Company')),
            ],
        ),
    ]
