# Generated by Django 2.1.7 on 2020-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200221_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyDbms',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyLatitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyLongitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companySystem',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dbComment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dbContractEndDate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dbContractStartDate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dbMainEmpId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dbSubEmpId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='saleEmpId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='solutionComment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='solutionContractEndDate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='solutionContractStartDate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='solutionMainEmpId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='solutionSubEmpId',
        ),
        migrations.AddField(
            model_name='company',
            name='companyComment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerType',
            field=models.CharField(blank=True, choices=[('실무', '실무'), ('영업', '영업'), ('세금', '세금')], max_length=10, null=True),
        ),
    ]
