# Generated by Django 2.1.7 on 2019-11-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191028_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
