# Generated by Django 2.1.7 on 2020-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
