# Generated by Django 2.1.7 on 2019-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_company_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerType',
            field=models.CharField(blank=True, choices=[('솔루션', '솔루션'), ('DB', 'DB'), ('영업', '영업'), ('세금', '세금')], max_length=10, null=True),
        ),
    ]
