# Generated by Django 2.1.7 on 2020-02-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_company_companyphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyNameKo',
        ),
    ]
