# Generated by Django 2.1.7 on 2020-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_customer_customertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyPhone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
