# Generated by Django 2.1.7 on 2020-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_company_companynameko'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyNameKo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
