# Generated by Django 2.1.7 on 2020-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_company_companynameko'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
