# Generated by Django 2.1.7 on 2020-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20200301_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyType',
            field=models.CharField(choices=[('발주처', '발주처'), ('외주업체', '외주업체'), ('기타', '기타')], default='기타', max_length=100),
        ),
    ]
