# Generated by Django 2.1.7 on 2020-02-04 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('centerId', models.AutoField(primary_key=True, serialize=False)),
                ('centerName', models.CharField(max_length=30)),
                ('centerStatus', models.CharField(default='Y', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CenterManager',
            fields=[
                ('centerManagerId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('centerManagerStatus', models.CharField(default='Y', max_length=10)),
                ('writeEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='CenterManagerEmp',
            fields=[
                ('managerId', models.AutoField(primary_key=True, serialize=False)),
                ('additionalArea', models.CharField(blank=True, max_length=30, null=True)),
                ('centerManagerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daesungwork.CenterManager')),
                ('cleanupArea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanupArea', to='daesungwork.Center')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('manageArea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manageArea', to='daesungwork.Center')),
            ],
        ),
    ]
