# Generated by Django 2.1.7 on 2020-02-03 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterManager',
            fields=[
                ('centerMangerId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('centerManagerStatus', models.CharField(default='Y', max_length=10)),
                ('writeEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
