# Generated by Django 2.1.7 on 2020-02-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
        ('daesungwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterManagerEmp',
            fields=[
                ('managerId', models.AutoField(primary_key=True, serialize=False)),
                ('manageArea', models.CharField(blank=True, max_length=30, null=True)),
                ('additionalArea', models.CharField(blank=True, max_length=30, null=True)),
                ('cleanupArea', models.CharField(blank=True, max_length=30, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
