# Generated by Django 2.1.7 on 2020-02-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('checkListId', models.AutoField(primary_key=True, serialize=False)),
                ('checkListName', models.CharField(max_length=30)),
                ('checkListStatus', models.CharField(default='Y', max_length=10)),
            ],
        ),
    ]
