# Generated by Django 2.1.7 on 2020-02-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0002_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmCheckList',
            fields=[
                ('confirmId', models.AutoField(primary_key=True, serialize=False)),
                ('confirmDate', models.DateField()),
                ('checkListStatus', models.CharField(choices=[('Y', '정상'), ('N', '이상')], default='Y', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='contract/%Y_%m')),
                ('checkListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daesungwork.CheckList')),
            ],
        ),
    ]
