# Generated by Django 2.1.7 on 2020-02-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0002_centermanageremp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('centerId', models.AutoField(primary_key=True, serialize=False)),
                ('centerName', models.CharField(max_length=30)),
                ('centerStatus', models.CharField(default='Y', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='centermanageremp',
            name='centerManagerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daesungwork.CenterManager'),
        ),
        migrations.AlterField(
            model_name='centermanageremp',
            name='cleanupArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanupArea', to='daesungwork.Center'),
        ),
        migrations.AlterField(
            model_name='centermanageremp',
            name='manageArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manageArea', to='daesungwork.Center'),
        ),
    ]
