# Generated by Django 2.1.7 on 2020-02-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0003_confirmchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmchecklist',
            name='centerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Center'),
        ),
        migrations.AlterField(
            model_name='confirmchecklist',
            name='checkListId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daesungwork.CheckList'),
        ),
    ]
