# Generated by Django 2.1.7 on 2020-02-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
        ('daesungwork', '0004_auto_20200205_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmchecklist',
            name='empId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.Employee'),
        ),
    ]
