# Generated by Django 2.1.7 on 2020-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0005_confirmchecklist_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmchecklist',
            name='file',
            field=models.FileField(upload_to='checkList/%Y_%m'),
        ),
    ]
