# Generated by Django 2.1.7 on 2020-02-24 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_company_companyphone'),
        ('daesungwork', '0008_auto_20200224_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleId', models.AutoField(primary_key=True, serialize=False)),
                ('saleDate', models.DateField()),
                ('revenueCompany', models.CharField(choices=[('대성종합상사', '대성종합상사'), ('대성어패럴', '대성어패럴')], max_length=20)),
                ('unitPrice', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('salePrice', models.IntegerField()),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Product')),
            ],
        ),
    ]
