# Generated by Django 2.1.7 on 2020-02-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0009_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Size'),
        ),
    ]
