# Generated by Django 2.1.7 on 2020-02-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0010_sale_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('affiliateId', models.AutoField(primary_key=True, serialize=False)),
                ('affiliateName', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='revenueCompany',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouseName',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Affiliate'),
        ),
    ]
