# Generated by Django 2.1.7 on 2020-02-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0011_auto_20200224_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daesungwork.Product'),
        ),
    ]
