# Generated by Django 2.1.7 on 2020-02-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0012_auto_20200224_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouseName',
        ),
    ]
