# Generated by Django 2.1.7 on 2020-02-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0013_remove_warehouse_warehousename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemaincategory',
            name='categoryStatus',
            field=models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousesubcategory',
            name='categoryStatus',
            field=models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=20),
        ),
    ]
