# Generated by Django 2.1.7 on 2020-02-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0014_auto_20200224_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPicture',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouseDrawing',
            field=models.FileField(blank=True, null=True, upload_to='warehouse/'),
        ),
    ]
