# Generated by Django 2.1.7 on 2020-02-25 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_auto_20200212_1322'),
        ('daesungwork', '0016_auto_20200225_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('dailyreportId', models.AutoField(primary_key=True, serialize=False)),
                ('workDate', models.DateField()),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('contents', models.TextField(help_text='상세 내용을 작성해 주세요.')),
                ('writeDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifyDatetime', models.DateTimeField()),
                ('writeEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
