# Generated by Django 2.1.7 on 2020-02-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0017_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('displayId', models.AutoField(primary_key=True, serialize=False)),
                ('postDate', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Size')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='dailyreport/'),
        ),
    ]
