# Generated by Django 2.1.7 on 2020-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0017_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='dailyreport/'),
        ),
    ]
