# Generated by Django 2.1.7 on 2020-02-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0018_auto_20200226_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
