# Generated by Django 2.1.7 on 2020-02-26 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0018_dailyreport_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='modifyDatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
