# Generated by Django 2.1.7 on 2020-02-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0020_auto_20200226_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daesungwork.Size'),
        ),
    ]
