# Generated by Django 2.1.7 on 2020-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0024_auto_20200226_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.CharField(default='Y', max_length=20),
        ),
    ]
