# Generated by Django 2.1.7 on 2020-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0025_product_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPicture',
            field=models.FileField(blank=True, default='product/noimage.png', null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouseDrawing',
            field=models.FileField(blank=True, default='warehouse/noimage.png', null=True, upload_to='warehouse/'),
        ),
    ]
