# Generated by Django 2.1.7 on 2020-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0019_auto_20200226_1433'),
        ('daesungwork', '0026_auto_20200226_1412'),
    ]

    operations = [
    ]
