# Generated by Django 2.1.7 on 2020-02-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0028_auto_20200226_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlocation',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productlocation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productlocation',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daesungwork.Warehouse'),
        ),
        migrations.DeleteModel(
            name='ProductLocation',
        ),
    ]
