# Generated by Django 2.1.7 on 2020-02-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0027_merge_20200227_0907'),
        ('daesungwork', '0029_auto_20200226_1735'),
    ]

    operations = [
    ]
