# Generated by Django 2.1.7 on 2020-02-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0030_merge_20200227_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('reproductionId', models.AutoField(primary_key=True, serialize=False)),
                ('postDate', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Size')),
            ],
        ),
    ]
