# Generated by Django 2.1.7 on 2020-02-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0031_auto_20200227_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='typeName',
        ),
    ]
