# Generated by Django 2.1.7 on 2020-02-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0031_reproduction'),
        ('daesungwork', '0032_auto_20200227_1625'),
    ]

    operations = [
    ]
