# Generated by Django 2.1.7 on 2020-02-27 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_company_companyphone'),
        ('daesungwork', '0033_merge_20200227_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('buyId', models.AutoField(primary_key=True, serialize=False)),
                ('buyDate', models.DateField()),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitPrice', models.IntegerField(blank=True, null=True)),
                ('salePrice', models.IntegerField()),
                ('vatPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Company')),
            ],
        ),
    ]
