# Generated by Django 2.1.7 on 2020-02-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0034_productcheck_stockcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcheck',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daesungwork.Size'),
        ),
    ]
