# Generated by Django 2.1.7 on 2020-02-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0036_stockcheck_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcheck',
            name='stockcheck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daesungwork.StockCheck'),
        ),
    ]
