# Generated by Django 2.1.7 on 2020-02-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0037_productcheck_stockcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcheck',
            name='stockcheck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daesungwork.StockCheck'),
        ),
    ]
