# Generated by Django 2.1.7 on 2020-02-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0038_auto_20200228_1314'),
        ('daesungwork', '0036_auto_20200227_1922'),
    ]

    operations = [
    ]
