# Generated by Django 2.1.7 on 2020-03-02 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_auto_20200212_1322'),
        ('daesungwork', '0039_merge_20200228_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('stockManagementId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('createdDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('managerEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
                ('productName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daesungwork.Product')),
                ('sizeName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daesungwork.Size')),
            ],
        ),
    ]
