# Generated by Django 2.1.7 on 2020-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0040_stockmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagement',
            name='typeName',
            field=models.CharField(choices=[('입고', '입고'), ('출고', '출고')], default='입고', max_length=10),
        ),
    ]
