# Generated by Django 2.1.7 on 2020-03-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0041_stockmanagement_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daesungwork.Affiliate'),
        ),
    ]
