# Generated by Django 2.1.7 on 2020-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0043_auto_20200311_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagement',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
