# Generated by Django 2.1.7 on 2020-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0044_stockmanagement_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
