# Generated by Django 2.1.7 on 2020-03-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daesungwork', '0045_sale_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='typeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daesungwork.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('typeName', 'modelName')},
        ),
    ]
