# Generated by Django 2.1.7 on 2020-02-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bookrental',
            fields=[
                ('rentalId', models.AutoField(primary_key=True, serialize=False)),
                ('rentDatetime', models.DateField(auto_now_add=True)),
                ('predictReturnDate', models.DateField(blank=True, null=True)),
                ('returnDate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Book')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
