# Generated by Django 2.1.7 on 2020-02-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrental',
            old_name='rentDatetime',
            new_name='rentDate',
        ),
    ]
