# Generated by Django 2.1.7 on 2020-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_auto_20200206_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrental',
            name='predictReturnDate',
        ),
        migrations.AddField(
            model_name='book',
            name='predictReturnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
