# Generated by Django 2.1.7 on 2020-02-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20200206_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='predictReturnDate',
        ),
        migrations.AddField(
            model_name='book',
            name='rentalId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply.Bookrental'),
        ),
        migrations.AddField(
            model_name='bookrental',
            name='predictReturnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
