# Generated by Django 2.1.7 on 2020-02-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
        ('supply', '0004_auto_20200206_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('savingId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('purchaseCompany', models.CharField(blank=True, max_length=100, null=True)),
                ('purchaseDate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('purchaseEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
            ],
        ),
    ]
