# Generated by Django 2.1.7 on 2020-02-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='standard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
