# Generated by Django 2.1.7 on 2020-02-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_auto_20200210_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saving',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingquantity',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
    ]
