# Generated by Django 2.1.7 on 2020-02-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_auto_20200221_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='money',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='quantity',
        ),
    ]
