# Generated by Django 2.1.7 on 2020-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0010_auto_20200221_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(default='#1', max_length=100),
        ),
    ]
