# Generated by Django 2.1.7 on 2020-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0013_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
