# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.forms.widgets
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('smtpServer', models.CharField(max_length=20)),
                ('smtpPort', models.CharField(max_length=10)),
                ('smtpEmail', models.CharField(max_length=100)),
                ('smtpPassword', models.CharField(max_length=20, verbose_name=django.forms.widgets.PasswordInput)),
                ('smtpSecure', models.CharField(blank=True, max_length=10, null=True)),
                ('smtpDatetime', models.DateTimeField(blank=True, null=True)),
                ('smtpStatus', models.CharField(default='정상', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdminVacation',
            fields=[
                ('vacationId', models.AutoField(primary_key=True, serialize=False)),
                ('vacationType', models.CharField(max_length=20)),
                ('vacationDays', models.FloatField()),
                ('creationDateTime', models.DateTimeField()),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertId', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('createdDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('clickedDatetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('attendanceDate', models.DateField()),
                ('attendanceTime', models.TimeField()),
                ('attendanceType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=100, unique=True)),
                ('deptLevel', models.IntegerField(default=0)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('departmentStatus', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('empCode', models.CharField(blank=True, max_length=20, null=True)),
                ('empName', models.CharField(max_length=10)),
                ('empManager', models.CharField(choices=[('Y', '부서장'), ('N', '팀원')], default='N', max_length=1)),
                ('empPhone', models.CharField(max_length=20)),
                ('empEmail', models.EmailField(max_length=254)),
                ('empDeptName', models.CharField(blank=True, max_length=30, null=True)),
                ('dispatchCompany', models.CharField(default='내근', max_length=100)),
                ('message', models.CharField(default='내근 업무 내용을 작성해 주세요.', help_text='내근 업무 내용을 작성해 주세요.', max_length=200)),
                ('empAuth', models.CharField(default='일반', max_length=10)),
                ('empRank', models.IntegerField(default=10)),
                ('empSalary', models.IntegerField(default=0)),
                ('empAnnualLeave', models.FloatField(default=0)),
                ('empSpecialLeave', models.FloatField(default=0)),
                ('empRewardAvailable', models.CharField(choices=[('가능', '가능'), ('불가능', '불가능')], default='가능', max_length=10)),
                ('empStartDate', models.DateField(blank=True, null=True)),
                ('empEndDate', models.DateField(blank=True, null=True)),
                ('empStamp', models.FileField(default='stamp/accepted.png', upload_to='stamp/')),
                ('empStatus', models.CharField(choices=[('Y', '재직'), ('N', '퇴사')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionId', models.AutoField(primary_key=True, serialize=False)),
                ('positionName', models.CharField(max_length=10)),
                ('positionSalary', models.IntegerField(default=0)),
                ('positionRank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['positionRank'],
            },
        ),
        migrations.CreateModel(
            name='Punctuality',
            fields=[
                ('punctualityId', models.AutoField(primary_key=True, serialize=False)),
                ('punctualityDate', models.DateField()),
                ('punctualityType', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnVacation',
            fields=[
                ('returnId', models.AutoField(primary_key=True, serialize=False)),
                ('returnDateTime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee')),
            ],
        ),
    ]
