# Generated by Django 2.1.7 on 2019-12-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=20)),
                ('deptLevel', models.IntegerField(default=0)),
                ('deptManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
                ('parentDept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='departmentName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department'),
        ),
    ]
