# Generated by Django 2.1.7 on 2019-07-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punctuality',
            fields=[
                ('punctualityId', models.AutoField(primary_key=True, serialize=False)),
                ('punctualityDate', models.DateField()),
                ('punctualityType', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
