# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrapay', '0002_auto_20200221_1622'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnvacation',
            name='vacationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Vacation'),
        ),
        migrations.AddField(
            model_name='punctuality',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='carId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extrapay.Car'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departmentName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='empPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='deptManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='parentDept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='alert',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='adminvacation',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
    ]
