# Generated by Django 2.1.7 on 2020-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200221_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empSpecialLeave2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='empSpecialLeave3',
            field=models.FloatField(default=0),
        ),
    ]
