# Generated by Django 2.1.7 on 2019-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20191206_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('smtpServer', models.CharField(max_length=20)),
                ('smtpPort', models.CharField(max_length=10)),
                ('smtpEmail', models.CharField(max_length=20)),
                ('smtpPassword', models.CharField(max_length=20)),
                ('smtpName', models.CharField(max_length=10)),
                ('smtpDatetime', models.DateTimeField()),
                ('smtpStatus', models.CharField(default='Y', max_length=10)),
            ],
        ),
    ]
