# Generated by Django 2.1.7 on 2019-12-23 10:13

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_adminemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemail',
            name='smtpPassword',
            field=models.CharField(max_length=20, verbose_name=django.forms.widgets.PasswordInput),
        ),
    ]
