# Generated by Django 2.1.7 on 2019-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20191223_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empDeptName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
