# Generated by Django 2.1.7 on 2019-10-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0003_car_fuel_oil'),
        ('hr', '0003_auto_20190731_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='carId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extrapay.Car'),
        ),
    ]
