# Generated by Django 2.1.7 on 2019-12-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20191223_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemail',
            name='smtpStatus',
            field=models.CharField(default='정상', max_length=10),
        ),
    ]
