# Generated by Django 2.1.7 on 2019-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20191223_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemail',
            name='smtpSecure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
