# Generated by Django 2.1.7 on 2019-12-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20191223_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminemail',
            name='smtpName',
        ),
    ]
