# Generated by Django 2.1.7 on 2019-12-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20191223_1228'),
        ('hr', '0005_auto_20191223_1702'),
    ]

    operations = [
    ]
