# Generated by Django 2.1.7 on 2019-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_merge_20191223_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empStamp',
            field=models.FileField(default='stamp/accepted.png', upload_to='stamp/'),
        ),
    ]
