# Generated by Django 2.1.7 on 2019-12-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_employee_empstamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVacation',
            fields=[
                ('vacationId', models.AutoField(primary_key=True, serialize=False)),
                ('vacationType', models.CharField(max_length=20)),
                ('vacationDays', models.FloatField()),
                ('creationDateTime', models.DateTimeField()),
                ('expirationDateTime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
