# Generated by Django 2.1.7 on 2019-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_adminvacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminvacation',
            name='expirationDateTime',
        ),
        migrations.AddField(
            model_name='adminvacation',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
