# Generated by Django 2.1.7 on 2019-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_auto_20191228_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empAnnualLeave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='empSpecialLeave',
            field=models.FloatField(default=0),
        ),
    ]
