# Generated by Django 2.1.7 on 2019-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_auto_20191228_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empRewardAvailable',
            field=models.CharField(default='불가능', max_length=10),
        ),
    ]
