# Generated by Django 2.1.7 on 2019-12-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_auto_20191228_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empRewardAvailable',
            field=models.CharField(choices=[('가능', '가능'), ('불가능', '불가능')], default='가능', max_length=10),
        ),
    ]
