# Generated by Django 2.1.7 on 2020-01-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_vacation_rewardvacationtype'),
        ('approval', '0016_auto_20200104_1523'),
        ('hr', '0020_auto_20191228_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnVacation',
            fields=[
                ('returnId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('documentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approval.Document')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee')),
                ('vacationId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Vacation')),
            ],
        ),
    ]
