# Generated by Django 2.1.7 on 2020-01-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_returnvacation_returndatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnvacation',
            name='documentId',
        ),
    ]
