# Generated by Django 2.1.7 on 2020-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_remove_returnvacation_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deptName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
