# Generated by Django 2.1.7 on 2020-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_auto_20200122_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='positionRank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='positionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
