# Generated by Django 2.1.7 on 2020-01-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_auto_20200122_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['positionRank']},
        ),
    ]
