# Generated by Django 2.1.7 on 2020-01-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_auto_20200122_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Position'),
        ),
    ]
