# Generated by Django 2.1.7 on 2020-01-31 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_auto_20200128_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertId', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('createdDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('clickedDatetime', models.DateTimeField(blank=True, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
