# Generated by Django 2.1.7 on 2020-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='departmentStatus',
            field=models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=10),
        ),
        migrations.AddField(
            model_name='department',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
