# Generated by Django 2.1.7 on 2020-03-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(blank=True, choices=[('전자결재', '전자결재'), ('의견', '의견'), ('유류비', '유류비'), ('기타', '기타')], max_length=20, null=True),
        ),
    ]
