# Generated by Django 2.1.7 on 2020-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_auto_20200212_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profilePhoto',
            field=models.FileField(blank=True, default='profile/default.png', null=True, upload_to='profile/'),
        ),
    ]
