# Generated by Django 2.1.7 on 2020-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_authorization_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menuName',
            new_name='mainCategory',
        ),
        migrations.AddField(
            model_name='menu',
            name='subCategory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
