# Generated by Django 2.1.7 on 2020-03-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_auto_20200311_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='menuId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='codeName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
