# Generated by Django 2.1.5 on 2019-04-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceboard',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='serviceboard',
            name='empDeptName',
        ),
        migrations.RemoveField(
            model_name='serviceboard',
            name='empName',
        ),
        migrations.RemoveField(
            model_name='serviceboard',
            name='serviceDate',
        ),
        migrations.RemoveField(
            model_name='serviceboard',
            name='serviceType',
        ),
        migrations.AlterField(
            model_name='board',
            name='boardWriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AlterField(
            model_name='serviceboard',
            name='serviceBoardWriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
    ]
