# Generated by Django 2.1.7 on 2020-03-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_alert_type'),
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('topExposure', models.CharField(choices=[('Y', '상단노출'), ('N', '해당없음')], default='N', max_length=10)),
                ('views', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('thumbnail', models.ImageField(max_length=200, upload_to='notice/thumbnail/%Y_%m')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notice/file/%Y_%m')),
                ('fileName', models.CharField(max_length=200)),
                ('fileSize', models.FloatField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('noticeCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noticeboard.NoticeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.Notice')),
            ],
        ),
        migrations.AddField(
            model_name='noticecategory',
            name='noticeList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticeboard.NoticeList'),
        ),
        migrations.AddField(
            model_name='notice',
            name='noticeCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticeboard.NoticeCategory'),
        ),
        migrations.AddField(
            model_name='notice',
            name='noticeSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticeboard.NoticeSubject'),
        ),
    ]
