# Generated by Django 2.1.7 on 2020-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20200327_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticecategory',
            name='orderNumber',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='noticelist',
            name='orderNumber',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='noticesubject',
            name='orderNumber',
            field=models.IntegerField(default=100),
        ),
    ]
