# Generated by Django 2.1.5 on 2019-04-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190329_1928'),
        ('noticeboard', '0003_auto_20190405_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceboard',
            name='serviceBoardWriter',
        ),
        migrations.RemoveField(
            model_name='serviceboard',
            name='serviceId',
        ),
        migrations.AddField(
            model_name='board',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport'),
        ),
        migrations.DeleteModel(
            name='Serviceboard',
        ),
    ]
