# Generated by Django 2.1.5 on 2019-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_auto_20190405_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardFiles',
            field=models.FileField(blank=True, null=True, upload_to='boardfiles/%Y_%m'),
        ),
    ]
