# Generated by Django 2.1.5 on 2019-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_auto_20190408_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardFiles',
            field=models.FileField(blank=True, null=True, upload_to='board/%Y_%m'),
        ),
    ]
