# Generated by Django 2.1.7 on 2019-07-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_contract_modifycontractpaper'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='contractId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract'),
        ),
    ]
