# Generated by Django 2.1.7 on 2020-02-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='service/%Y_%m')),
                ('fileName', models.CharField(max_length=200)),
                ('fileSize', models.FloatField()),
                ('documentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Servicereport')),
            ],
        ),
    ]
