# Generated by Django 2.1.5 on 2019-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacationEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacationStartDate',
            field=models.DateField(),
        ),
    ]
