# Generated by Django 2.1.7 on 2019-09-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicereport_contractid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('geolocationId', models.AutoField(primary_key=True, serialize=False)),
                ('startLatitude', models.FloatField()),
                ('startLongitude', models.FloatField()),
                ('endLatitude', models.FloatField()),
                ('endLongitude', models.FloatField()),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport')),
            ],
        ),
    ]
