# Generated by Django 2.1.7 on 2020-02-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefile',
            old_name='documentId',
            new_name='serviceId',
        ),
    ]
