# Generated by Django 2.1.7 on 2019-12-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191224_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacationcategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacation',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacationStatus',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacationCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Vacationcategory'),
        ),
    ]
