# Generated by Django 2.1.7 on 2019-09-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='endLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='endLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
