# Generated by Django 2.1.7 on 2019-12-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0015_remove_document_vacationid'),
        ('service', '0003_auto_20191227_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='documentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Document'),
        ),
    ]
