# Generated by Django 2.1.7 on 2020-03-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200223_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='companyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Company'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='companyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Company'),
        ),
    ]
