# Generated by Django 2.1.7 on 2019-12-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_vacation_documentid'),
        ('service', '0003_auto_20191226_1553'),
    ]

    operations = [
    ]
