# Generated by Django 2.1.7 on 2020-01-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_vacation_documentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='rewardVacationType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
