# Generated by Django 2.1.7 on 2020-03-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200303_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='serviceDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
