# Generated by Django 2.1.7 on 2020-01-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_vacation_rewardvacationtype'),
        ('service', '0005_merge_20191228_2017'),
    ]

    operations = [
    ]
