# Generated by Django 2.1.7 on 2019-10-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20191010_1025'),
        ('service', '0005_auto_20191008_1018'),
    ]

    operations = [
    ]
