# Generated by Django 2.1.7 on 2020-01-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_vacation_rewardvacationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='dashboardStatus',
            field=models.CharField(default='Y', max_length=10),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='punctualityStatus',
            field=models.CharField(default='Y', max_length=10),
        ),
    ]
