# Generated by Django 2.1.7 on 2020-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200303_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='calendarStatus',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=10),
        ),
    ]
