# Generated by Django 2.1.7 on 2020-01-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200122_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='dashboardStatus',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='punctualityStatus',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=10),
        ),
    ]
