# Generated by Django 2.1.7 on 2019-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20191010_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='directgo',
            field=models.CharField(choices=[('N', 'N'), ('B', 'B'), ('S', 'S'), ('E', 'E'), ('Y', 'Y')], default='N', max_length=1),
        ),
    ]
