# Generated by Django 2.1.7 on 2020-01-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200122_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['orderNumber', 'typeName']},
        ),
    ]
