# Generated by Django 2.1.7 on 2020-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicereport_calendarstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='calendarStatus',
            field=models.CharField(choices=[('Y', '전체노출'), ('M', '개인노출'), ('N', '미노출')], default='Y', max_length=10),
        ),
    ]
