# Generated by Django 2.1.7 on 2019-10-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20191010_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='serviceStatus',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
