# Generated by Django 2.1.7 on 2019-10-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20191010_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('oilType', models.CharField(max_length=10)),
                ('carType', models.CharField(max_length=10)),
                ('kpl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuelId', models.AutoField(primary_key=True, serialize=False)),
                ('distance1', models.FloatField()),
                ('distance2', models.FloatField()),
                ('totalDistance', models.FloatField()),
                ('fuelStatus', models.CharField(default='N', max_length=1)),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport')),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('oilId', models.AutoField(primary_key=True, serialize=False)),
                ('oilDate', models.DateField()),
                ('oilMoney', models.FloatField()),
                ('mpk', models.IntegerField()),
                ('carType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Car')),
            ],
        ),
    ]
