# Generated by Django 2.1.7 on 2020-02-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20200122_1716'),
        ('service', '0006_merge_20200113_1034'),
    ]

    operations = [
    ]
