# Generated by Django 2.1.7 on 2020-02-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
        ('service', '0009_merge_20200203_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participantId', models.AutoField(primary_key=True, serialize=False)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('주간회의', '주간회의'), ('월간회의', '월간회의'), ('전체회의', '전체회의'), ('기타', '기타')], max_length=100)),
                ('reportDate', models.DateField()),
                ('reportTime', models.TimeField()),
                ('location', models.CharField(default='회의실', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('contents', models.TextField()),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='reportId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Report'),
        ),
    ]
