# Generated by Django 2.1.7 on 2019-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20191011_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='comment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuelMoney',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
