# Generated by Django 2.1.7 on 2020-02-04 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20200131_1720'),
        ('service', '0010_auto_20200204_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='modifyDatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='writeDatetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer', to='hr.Employee'),
        ),
    ]
