# Generated by Django 2.1.7 on 2020-02-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20200204_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='companyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Company'),
        ),
    ]
