# Generated by Django 2.1.7 on 2019-10-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrapay', '0001_initial'),
        ('service', '0011_auto_20191011_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='overHourId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extrapay.OverHour'),
        ),
    ]
