# Generated by Django 2.1.7 on 2019-10-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20191014_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='serviceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport', unique=True),
        ),
    ]
