# Generated by Django 2.1.7 on 2019-10-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20191014_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='serviceId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Servicereport'),
        ),
    ]
