# Generated by Django 2.1.7 on 2019-10-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20191014_1734'),
        ('service', '0012_servicereport_overhourid'),
    ]

    operations = [
    ]
