# Generated by Django 2.1.7 on 2019-10-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_merge_20191014_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='serviceId',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='carId',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
        migrations.DeleteModel(
            name='Oil',
        ),
    ]
