# Generated by Django 2.1.7 on 2019-10-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20191014_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='overHourId',
        ),
    ]
