# Generated by Django 2.1.7 on 2019-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_servicereport_overhourid'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='distanceCode',
            field=models.IntegerField(default=0),
        ),
    ]
