# Generated by Django 2.1.7 on 2019-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20191018_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
