# Generated by Django 2.1.7 on 2019-10-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_geolocation_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='path',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='ArrayField',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
