# Generated by Django 2.1.7 on 2019-10-20 00:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20191019_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='ArrayField',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='path',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, default='', null=True, size=None),
        ),
    ]
