# Generated by Django 2.1.7 on 2019-10-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20191020_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
