# Generated by Django 2.1.7 on 2019-10-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_merge_20191011_0858'),
        ('service', '0022_auto_20191020_0018'),
    ]

    operations = [
    ]
