# Generated by Django 2.1.7 on 2019-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_merge_20191022_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='finishAlias',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
