# Generated by Django 2.1.7 on 2019-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_geolocation_finishalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='finishAlias',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='distanceRatio',
            field=models.FloatField(default=1.0),
        ),
    ]
