# Generated by Django 2.1.7 on 2019-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_auto_20191023_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='distanceRatio',
            field=models.FloatField(default=1.2),
        ),
    ]
