# Generated by Django 2.1.7 on 2019-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_auto_20191023_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='beginLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='endLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='finishLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='startLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
