# Generated by Django 2.1.7 on 2019-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_auto_20191023_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
