# Generated by Django 2.1.7 on 2019-10-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_geolocation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='tollMoney',
            field=models.IntegerField(default=0),
        ),
    ]
