# Generated by Django 2.1.7 on 2019-10-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approvalId', models.AutoField(primary_key=True, serialize=False)),
                ('approvalStep', models.IntegerField(default=0)),
                ('approvalStatus', models.CharField(default='대기', max_length=10)),
                ('comment', models.CharField(default='', max_length=200)),
                ('approvalDatetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Approvalcategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('approvalCategory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docuform',
            fields=[
                ('formId', models.AutoField(primary_key=True, serialize=False)),
                ('formNumber', models.IntegerField(unique=True)),
                ('formHtml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('documentNumber', models.CharField(default='', max_length=100)),
                ('preservationYear', models.IntegerField(default=9999)),
                ('securityLevel', models.CharField(default='S', max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('contentHtml', models.TextField()),
                ('writeDatetime', models.DateTimeField()),
                ('modifyDatetime', models.DateTimeField()),
                ('draftDatetime', models.DateTimeField(blank=True, null=True)),
                ('approveDatetime', models.DateTimeField(blank=True, null=True)),
                ('documentStatus', models.CharField(default='임시', max_length=10)),
                ('formId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Docuform')),
                ('writeEmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Documentcategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('firstCategory', models.CharField(default='공통', max_length=20)),
                ('secondCategory', models.CharField(default='공통', max_length=20)),
                ('thirdCategory', models.CharField(default='공통', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documentfile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='document/%Y_%m')),
                ('fileName', models.CharField(max_length=200)),
                ('fileSize', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='docuform',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Documentcategory'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approvalCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approval.Approvalcategory'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approvalEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='approval',
            name='documentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Document'),
        ),
    ]
