# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approvalId', models.AutoField(primary_key=True, serialize=False)),
                ('approvalStep', models.IntegerField(default=0)),
                ('approvalCategory', models.CharField(choices=[('신청', '신청'), ('승인', '승인'), ('참조', '참조'), ('결재', '결재'), ('합의', '합의'), ('재무합의', '재무합의')], default='신청', max_length=20)),
                ('approvalStatus', models.CharField(default='대기', max_length=10)),
                ('comment', models.CharField(default='', max_length=200)),
                ('approvalDatetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Approvalcategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('approvalCategory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Approvalform',
            fields=[
                ('approvalId', models.AutoField(primary_key=True, serialize=False)),
                ('approvalStep', models.IntegerField(default=0)),
                ('approvalCategory', models.CharField(default='처리', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('documentNumber', models.CharField(default='', max_length=100)),
                ('preservationYear', models.IntegerField(default=9999)),
                ('securityLevel', models.CharField(default='S', max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('contentHtml', models.TextField()),
                ('writeDatetime', models.DateTimeField()),
                ('modifyDatetime', models.DateTimeField()),
                ('draftDatetime', models.DateTimeField(blank=True, null=True)),
                ('approveDatetime', models.DateTimeField(blank=True, null=True)),
                ('documentStatus', models.CharField(default='임시', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Documentcategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('firstCategory', models.CharField(default='공통', max_length=20)),
                ('secondCategory', models.CharField(default='공통', max_length=20)),
                ('thirdCategory', models.CharField(default='공통', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documentcomment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Documentfile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='document/%Y_%m')),
                ('fileName', models.CharField(max_length=200)),
                ('fileSize', models.FloatField()),
                ('documentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Documentform',
            fields=[
                ('formId', models.AutoField(primary_key=True, serialize=False)),
                ('formNumber', models.IntegerField(default=0)),
                ('preservationYear', models.IntegerField(default=9999)),
                ('securityLevel', models.CharField(default='S', max_length=1)),
                ('approvalFormat', models.CharField(choices=[('신청', '신청'), ('결재', '결재')], default='신청', max_length=10)),
                ('formTitle', models.CharField(max_length=200)),
                ('formHtml', models.TextField()),
                ('comment', models.CharField(default='', max_length=200)),
                ('copyAuth', models.CharField(default='Y', max_length=10)),
                ('mailAuth', models.CharField(default='Y', max_length=10)),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Documentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Relateddocument',
            fields=[
                ('relatedId', models.AutoField(primary_key=True, serialize=False)),
                ('documentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentId2', to='approval.Document')),
                ('relatedDocumentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatedDocumentId', to='approval.Document')),
            ],
        ),
    ]
