# Generated by Django 2.1.7 on 2019-10-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentform',
            name='formNumber',
            field=models.IntegerField(default=0),
        ),
    ]
