# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('approval', '0001_initial'),
        ('sales', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='documentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='contractId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract'),
        ),
        migrations.AddField(
            model_name='document',
            name='formId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Documentform'),
        ),
        migrations.AddField(
            model_name='document',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Servicereport'),
        ),
        migrations.AddField(
            model_name='document',
            name='writeEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='approvalEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='formId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Documentform'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approvalEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='approval',
            name='documentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Document'),
        ),
    ]
