# Generated by Django 2.1.7 on 2019-11-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20191031_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentform',
            name='preservationYear',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='documentform',
            name='securityLevel',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
