# Generated by Django 2.1.7 on 2019-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20191111_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='fileSize',
            field=models.FloatField(),
        ),
    ]
