# Generated by Django 2.1.7 on 2019-11-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20191111_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentform',
            name='approvalFormat',
            field=models.CharField(choices=[('신청', '신청'), ('결재', '결재')], default='신청', max_length=10),
        ),
    ]
