# Generated by Django 2.1.7 on 2019-11-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_auto_20191115_1534'),
        ('approval', '0005_auto_20191115_1024'),
    ]

    operations = [
    ]
