# Generated by Django 2.1.7 on 2019-11-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_merge_20191115_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvalcategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('approvalCategory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relateddocument',
            fields=[
                ('relatedId', models.AutoField(primary_key=True, serialize=False)),
                ('documentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentId2', to='approval.Document')),
                ('relatedDocumentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatedDocumentId', to='approval.Document')),
            ],
        ),
    ]
