# Generated by Django 2.1.7 on 2019-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_approvalcategory_relateddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approvalCategory',
            field=models.CharField(choices=[('신청', '신청'), ('승인', '승인'), ('참조', '참조'), ('결재', '결재'), ('합의', '합의'), ('재무합의', '재무합의')], default='신청', max_length=20),
        ),
    ]
