# Generated by Django 2.1.7 on 2019-11-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_contractfile'),
        ('service', '0001_initial'),
        ('approval', '0009_auto_20191120_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contractId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract'),
        ),
        migrations.AddField(
            model_name='document',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Servicereport'),
        ),
    ]
