# Generated by Django 2.1.7 on 2019-12-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20191206_1732'),
        ('approval', '0010_auto_20191126_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentcomment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee')),
                ('documentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Document')),
            ],
        ),
    ]
