# Generated by Django 2.1.7 on 2019-12-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0011_documentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clicked',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
