# Generated by Django 2.1.7 on 2019-12-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0012_document_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='clicked',
        ),
    ]
