# Generated by Django 2.1.7 on 2019-12-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191224_1456'),
        ('approval', '0013_remove_document_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vacationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Vacation'),
        ),
    ]
