# Generated by Django 2.1.7 on 2019-12-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0014_document_vacationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='vacationId',
        ),
    ]
