# Generated by Django 2.1.7 on 2020-01-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0015_remove_document_vacationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentform',
            name='copyAuth',
            field=models.CharField(default='Y', max_length=10),
        ),
        migrations.AddField(
            model_name='documentform',
            name='mailAuth',
            field=models.CharField(default='Y', max_length=10),
        ),
    ]
