# Generated by Django 2.1.7 on 2020-04-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0016_auto_20200104_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='writeEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentWriteEmp', to='hr.Employee'),
        ),
    ]
