# Generated by Django 2.1.7 on 2019-12-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0018_auto_20191212_1104'),
        ('hr', '0002_auto_20191206_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('approvalLogId', models.AutoField(primary_key=True, serialize=False)),
                ('toEmail', models.CharField(max_length=50)),
                ('approvalDatetime', models.DateTimeField()),
                ('approvalUrl', models.CharField(max_length=100)),
                ('contractId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('downloadLogId', models.AutoField(primary_key=True, serialize=False)),
                ('downloadDatetime', models.DateTimeField()),
                ('downloadUrl', models.CharField(max_length=100)),
                ('contractId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('orderLogId', models.AutoField(primary_key=True, serialize=False)),
                ('toEmail', models.CharField(max_length=50)),
                ('orderDatetime', models.DateTimeField()),
                ('orderUrl', models.CharField(max_length=100)),
                ('contractId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
