# Generated by Django 2.1.7 on 2020-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0002_auto_20200221_1622'),
        ('hr', '0002_auto_20200221_1622'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('approvalLogId', models.AutoField(primary_key=True, serialize=False)),
                ('toEmail', models.CharField(max_length=50)),
                ('approvalDatetime', models.DateTimeField()),
                ('approvalStatus', models.CharField(default='전송성공', max_length=20)),
                ('approvalError', models.CharField(blank=True, max_length=100, null=True)),
                ('documentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Document')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContractLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('changeCount', models.IntegerField(default=1)),
                ('beforeSalePrice', models.BigIntegerField()),
                ('beforeProfitPrice', models.BigIntegerField()),
                ('beforeProfitRatio', models.FloatField()),
                ('afterSalePrice', models.BigIntegerField()),
                ('afterProfitPrice', models.BigIntegerField()),
                ('afterProfitRatio', models.FloatField()),
                ('diffSalePrice', models.BigIntegerField()),
                ('diffProfitPrice', models.BigIntegerField()),
                ('diffProfitRatio', models.FloatField()),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
                ('empId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('downloadLogId', models.AutoField(primary_key=True, serialize=False)),
                ('downloadDatetime', models.DateTimeField()),
                ('downloadType', models.CharField(blank=True, max_length=50, null=True)),
                ('downloadName', models.CharField(blank=True, max_length=100, null=True)),
                ('downloadUrl', models.CharField(max_length=100)),
                ('contractId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('orderLogId', models.AutoField(primary_key=True, serialize=False)),
                ('toEmail', models.CharField(max_length=50)),
                ('orderDatetime', models.DateTimeField()),
                ('orderStatus', models.CharField(default='전송성공', max_length=20)),
                ('orderError', models.CharField(blank=True, max_length=100, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Purchaseorder')),
            ],
        ),
    ]
