# Generated by Django 2.1.7 on 2019-12-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='downloadType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
