# Generated by Django 2.1.7 on 2019-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_downloadlog_downloadtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='downloadName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
