# Generated by Django 2.1.7 on 2019-12-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0011_documentcomment'),
        ('logs', '0003_downloadlog_downloadname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallog',
            name='approvalUrl',
        ),
        migrations.RemoveField(
            model_name='approvallog',
            name='contractId',
        ),
        migrations.AddField(
            model_name='approvallog',
            name='documentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.Document'),
        ),
    ]
