# Generated by Django 2.1.7 on 2019-12-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20191218_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='orderUrl',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='orderError',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='orderStatus',
            field=models.CharField(default='전송성공', max_length=20),
        ),
    ]
