# Generated by Django 2.1.7 on 2019-12-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20191218_1503'),
        ('logs', '0006_auto_20191219_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='contractId',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Purchaseorder'),
        ),
    ]
