# Generated by Django 2.1.7 on 2019-12-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20191219_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='documentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Document'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Purchaseorder'),
        ),
    ]
