# Generated by Django 2.1.7 on 2020-01-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_remove_returnvacation_documentid'),
        ('sales', '0031_auto_20200120_1812'),
        ('logs', '0008_auto_20191219_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractlog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('changeCount', models.IntegerField(default=1)),
                ('beforeSalePrice', models.BigIntegerField()),
                ('beforeProfitPrice', models.BigIntegerField()),
                ('beforeProfitRatio', models.FloatField()),
                ('afterSalePrice', models.BigIntegerField()),
                ('afterProfitPrice', models.BigIntegerField()),
                ('afterProfitRatio', models.FloatField()),
                ('diffSalePrice', models.BigIntegerField()),
                ('diffProfitPrice', models.BigIntegerField()),
                ('diffProfitRatio', models.FloatField()),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
                ('empId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
            ],
        ),
    ]
