# Generated by Django 2.1.7 on 2019-05-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractId', models.AutoField(primary_key=True, serialize=False)),
                ('contractName', models.CharField(max_length=200)),
                ('empName', models.CharField(max_length=10)),
                ('empDeptName', models.CharField(max_length=30)),
                ('saleCustomerName', models.CharField(max_length=10)),
                ('endCustomerName', models.CharField(max_length=10)),
                ('category', models.TextField(blank=True, null=True)),
                ('saleType', models.CharField(choices=[('직판', '직판'), ('T1', 'T1'), ('T2', 'T2')], default='직판', max_length=10)),
                ('saleIndustry', models.CharField(choices=[('금융', '금융'), ('공공', '공공'), ('제조', '제조'), ('통신', '통신'), ('기타', '기타')], default='금융', max_length=10)),
                ('predictSalePrice', models.IntegerField()),
                ('predictProfitPrice', models.IntegerField()),
                ('predictProfitRatio', models.FloatField()),
                ('predictContractDate', models.DateField()),
                ('salePrice', models.IntegerField()),
                ('profitPrice', models.IntegerField()),
                ('profitRatio', models.FloatField()),
                ('contractDate', models.DateField()),
                ('contractStep', models.CharField(choices=[('Opportunity', 'Opportunity'), ('Firm', 'Firm'), ('Drop', 'Drop')], default='Opportunity', max_length=20)),
                ('contractStartDate', models.DateField()),
                ('contractEndDate', models.DateField()),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('endCompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endCompanyName', to='client.Company')),
                ('endCustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endCustomerId', to='client.Customer')),
                ('saleCompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleCompanyName', to='client.Company')),
                ('saleCustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleCustomerId', to='client.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenueId', models.AutoField(primary_key=True, serialize=False)),
                ('revenueName', models.CharField(max_length=200)),
                ('salePrice', models.IntegerField()),
                ('billingDate', models.DateField()),
                ('collectDate', models.DateField()),
                ('revenueStep', models.CharField(choices=[('Complete', 'Complete'), ('수금완료', '수금완료')], default='Opportunity', max_length=20)),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
            ],
        ),
    ]
