# Generated by Django 2.1.7 on 2019-05-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('mainCategory', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractId', models.AutoField(primary_key=True, serialize=False)),
                ('contractCode', models.CharField(max_length=30)),
                ('contractName', models.CharField(max_length=200)),
                ('empName', models.CharField(max_length=10)),
                ('empDeptName', models.CharField(max_length=30)),
                ('saleCustomerName', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('saleType', models.CharField(choices=[('직판', '직판'), ('T1', 'T1'), ('T2', 'T2')], default='직판', max_length=10)),
                ('saleIndustry', models.CharField(choices=[('금융', '금융'), ('공공', '공공'), ('제조', '제조'), ('통신', '통신'), ('기타', '기타')], default='금융', max_length=10)),
                ('salePrice', models.IntegerField()),
                ('profitPrice', models.IntegerField()),
                ('profitRatio', models.FloatField()),
                ('contractDate', models.DateField()),
                ('contractStep', models.CharField(choices=[('Opportunity', 'Opportunity'), ('Firm', 'Firm'), ('Drop', 'Drop')], default='Opportunity', max_length=20)),
                ('contractStartDate', models.DateField(blank=True, null=True)),
                ('contractEndDate', models.DateField(blank=True, null=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('endCompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endCompanyName', to='client.Company')),
                ('saleCompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleCompanyName', to='client.Company')),
                ('saleCustomerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleCustomerId', to='client.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Contractitem',
            fields=[
                ('contractItemId', models.AutoField(primary_key=True, serialize=False)),
                ('mainCategory', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
                ('itemName', models.CharField(max_length=50)),
                ('itemPrice', models.IntegerField()),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goalId', models.AutoField(primary_key=True, serialize=False)),
                ('empDeptName', models.CharField(max_length=30)),
                ('empName', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('sales1', models.IntegerField()),
                ('sales2', models.IntegerField()),
                ('sales3', models.IntegerField()),
                ('sales4', models.IntegerField()),
                ('sales5', models.IntegerField()),
                ('sales6', models.IntegerField()),
                ('sales7', models.IntegerField()),
                ('sales8', models.IntegerField()),
                ('sales9', models.IntegerField()),
                ('sales10', models.IntegerField()),
                ('sales11', models.IntegerField()),
                ('sales12', models.IntegerField()),
                ('salesq1', models.IntegerField()),
                ('salesq2', models.IntegerField()),
                ('salesq3', models.IntegerField()),
                ('salesq4', models.IntegerField()),
                ('profit1', models.IntegerField()),
                ('profit2', models.IntegerField()),
                ('profit3', models.IntegerField()),
                ('profit4', models.IntegerField()),
                ('profit5', models.IntegerField()),
                ('profit6', models.IntegerField()),
                ('profit7', models.IntegerField()),
                ('profit8', models.IntegerField()),
                ('profit9', models.IntegerField()),
                ('profit10', models.IntegerField()),
                ('profit11', models.IntegerField()),
                ('profit12', models.IntegerField()),
                ('profitq1', models.IntegerField()),
                ('profitq2', models.IntegerField()),
                ('profitq3', models.IntegerField()),
                ('profitq4', models.IntegerField()),
                ('yearSalesSum', models.IntegerField()),
                ('yearProfitSum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenueId', models.AutoField(primary_key=True, serialize=False)),
                ('revenuePrice', models.IntegerField()),
                ('revenueProfitPrice', models.IntegerField()),
                ('billingDate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
            ],
        ),
    ]
