# Generated by Django 2.1.7 on 2019-05-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='category',
        ),
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
