# Generated by Django 2.1.7 on 2020-02-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='saleIndustry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.SaleindustryCategory'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='saleType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.SaletypeCategory'),
        ),
    ]
