# Generated by Django 2.1.7 on 2019-11-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractfile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileCategory', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=200)),
                ('fileSize', models.FloatField()),
                ('file', models.FileField(upload_to='contract/%Y_%m')),
                ('contractId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract')),
            ],
        ),
    ]
