# Generated by Django 2.1.7 on 2019-05-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category1',
            new_name='mainCategory',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category2',
            new_name='subCategory',
        ),
    ]
