# Generated by Django 2.1.7 on 2019-05-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endCompanyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endCompanyName', to='client.Company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='saleType',
            field=models.CharField(choices=[('직판', '직판'), ('T1', 'T1'), ('T2', 'T2'), ('기타', '기타')], default='직판', max_length=10),
        ),
    ]
