# Generated by Django 2.1.7 on 2019-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='modifyContractPaper',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=20, null=True),
        ),
    ]
