# Generated by Django 2.1.7 on 2019-08-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_contract_modifycontractpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('costId', models.AutoField(primary_key=True, serialize=False)),
                ('costCompany', models.CharField(max_length=20)),
                ('billingDate', models.DateField(blank=True, null=True)),
                ('billingTime', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
            ],
        ),
    ]
