# Generated by Django 2.1.7 on 2020-03-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200221_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endCompanyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endCompanyName', to='client.Company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='saleCompanyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleCompanyName', to='client.Company'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchaseCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Company'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenueCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Company'),
        ),
    ]
