# Generated by Django 2.1.7 on 2019-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190509_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='billingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='collectDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='collectPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='predictCollectDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenueStep',
            field=models.CharField(choices=[('Firm', 'Firm'), ('Complete', 'Complete'), ('분납', '분납'), ('수금완료', '수금완료')], default='Firm', max_length=20),
        ),
    ]
