# Generated by Django 2.1.7 on 2020-03-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200301_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='itemTotalPrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='itemVatPrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='itemPrice',
            field=models.BigIntegerField(default=0),
        ),
    ]
