# Generated by Django 2.1.7 on 2020-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200303_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontractitem',
            name='itemTotalPrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasecontractitem',
            name='itemVatPrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasecontractitem',
            name='itemPrice',
            field=models.BigIntegerField(default=0),
        ),
    ]
