# Generated by Django 2.1.7 on 2019-11-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20191126_1426'),
        ('sales', '0003_contractfile_uploaddatetime'),
    ]

    operations = [
    ]
