# Generated by Django 2.1.7 on 2019-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_cost_costprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseId', models.AutoField(primary_key=True, serialize=False)),
                ('expenseType', models.CharField(blank=True, max_length=20, null=True)),
                ('expenseDept', models.CharField(blank=True, max_length=20, null=True)),
                ('expenseMain', models.CharField(blank=True, max_length=50, null=True)),
                ('expenseSub', models.CharField(blank=True, max_length=50, null=True)),
                ('expenseMoney', models.IntegerField(default=0)),
                ('expenseDate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
