# Generated by Django 2.1.7 on 2019-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_cost_costprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='판관비', max_length=100)),
                ('money', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
