# Generated by Django 2.1.7 on 2019-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseStatus',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
