# Generated by Django 2.1.7 on 2019-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20191126_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetypeb',
            name='classification',
            field=models.CharField(choices=[('상품_HW', '상품_HW'), ('상품_SW', '상품_SW'), ('유지보수_HW', '유지보수_HW'), ('유지보수_SW', '유지보수_SW'), ('HW', 'HW'), ('SW', 'SW'), ('PM상주', 'PM상주'), ('기타', '기타')], max_length=20),
        ),
    ]
