# Generated by Django 2.1.7 on 2019-09-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_expenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
