# Generated by Django 2.1.7 on 2019-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_expense_expensestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseGroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
