# Generated by Django 2.1.7 on 2019-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_expense_expensestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='incentivePrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='incentiveProfitPrice',
            field=models.BigIntegerField(default=0),
        ),
    ]
