# Generated by Django 2.1.7 on 2019-09-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20190926_1324'),
        ('sales', '0007_expense_expensegroup'),
    ]

    operations = [
    ]
