# Generated by Django 2.1.7 on 2019-11-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_merge_20191127_0846'),
        ('sales', '0007_auto_20191127_1527'),
    ]

    operations = [
    ]
