# Generated by Django 2.1.7 on 2019-09-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20190731_1350'),
        ('sales', '0008_merge_20190926_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('accelerationId', models.AutoField(primary_key=True, serialize=False)),
                ('accelerationYear', models.IntegerField()),
                ('accelerationQuarter', models.IntegerField(default=0)),
                ('accelerationMin', models.IntegerField()),
                ('accelerationMax', models.IntegerField()),
                ('accelerationRatio', models.IntegerField()),
                ('accelerationAcc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('incentiveId', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('salary', models.BigIntegerField()),
                ('bettingRatio', models.IntegerField()),
                ('basicSalary', models.BigIntegerField()),
                ('bettingSalary', models.BigIntegerField()),
                ('achieveIncentive', models.BigIntegerField(default=0)),
                ('achieveAward', models.BigIntegerField(default=0)),
                ('incentiveStatus', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
