# Generated by Django 2.1.7 on 2019-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_acceleration_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='newCompany',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=10),
        ),
    ]
