# Generated by Django 2.1.7 on 2019-11-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20191128_1105'),
        ('sales', '0009_contractfile_uploademp'),
    ]

    operations = [
    ]
