# Generated by Django 2.1.7 on 2019-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_contract_newcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='incentiveReason',
            field=models.CharField(default='계산서미발행', max_length=20),
        ),
    ]
