# Generated by Django 2.1.7 on 2019-10-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20190731_1350'),
        ('sales', '0011_revenue_incentivereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='edirDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='editEmpId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editEmpId', to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='writeDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='writeEmpId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeEmpId', to='hr.Employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleEmpId', to='hr.Employee'),
        ),
    ]
