# Generated by Django 2.1.7 on 2019-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20191018_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='edirDatetime',
            new_name='editDatetime',
        ),
    ]
