# Generated by Django 2.1.7 on 2019-12-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20191203_1300'),
        ('sales', '0012_auto_20191203_1012'),
    ]

    operations = [
    ]
