# Generated by Django 2.1.7 on 2019-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_merge_20191203_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='confirmComment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmContents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmCustomer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
