# Generated by Django 2.1.7 on 2019-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20191204_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='confirmDatetime',
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
