# Generated by Django 2.1.7 on 2019-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_purchasecategory_purchasefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetypeb',
            name='sites',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetypeb',
            name='times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
