# Generated by Django 2.1.7 on 2019-12-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20191218_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderform',
            name='formTitle',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
