# Generated by Django 2.1.7 on 2019-12-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20191218_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderfile',
            name='purchaseCompany',
        ),
    ]
