# Generated by Django 2.1.7 on 2020-01-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_relatedpurchaseestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classificationId', models.AutoField(primary_key=True, serialize=False)),
                ('mainCategory', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
            ],
        ),
    ]
