# Generated by Django 2.1.7 on 2020-01-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_customer_customertype'),
        ('sales', '0024_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasecontractitem',
            fields=[
                ('contractItemId', models.AutoField(primary_key=True, serialize=False)),
                ('mainCategory', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
                ('itemName', models.CharField(max_length=50)),
                ('itemPrice', models.BigIntegerField()),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Company')),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
            ],
        ),
    ]
