# Generated by Django 2.1.7 on 2020-01-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20200105_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='modifyContract',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contractId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Contract'),
        ),
    ]
