# Generated by Django 2.1.7 on 2020-01-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_auto_20191228_2126'),
        ('sales', '0027_auto_20200110_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='empId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee'),
        ),
    ]
