# Generated by Django 2.1.7 on 2020-01-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_contractlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractlog',
            name='contractId',
        ),
        migrations.RemoveField(
            model_name='contractlog',
            name='empId',
        ),
        migrations.DeleteModel(
            name='Contractlog',
        ),
    ]
