# Generated by Django 2.1.7 on 2020-01-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_auto_20200122_1435'),
        ('sales', '0031_auto_20200120_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractcomment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Employee')),
                ('contractId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Contract')),
            ],
        ),
    ]
