# Generated by Django 2.1.7 on 2020-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20200120_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='revenueStatus',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
