# Generated by Django 2.1.7 on 2020-01-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_contractcomment'),
        ('sales', '0032_revenue_revenuestatus'),
    ]

    operations = [
    ]
