# Generated by Django 2.1.7 on 2020-01-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_auto_20200128_2251'),
        ('sales', '0033_merge_20200129_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveDept',
            fields=[
                ('incentiveDeptId', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('deptName', models.CharField(default='', max_length=100)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
