# Generated by Django 2.1.7 on 2020-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_incentivedept'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleindustryCategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('saleIndustryName', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaletypeCategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('saleTypeName', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractStep',
            field=models.CharField(choices=[('예정', '예정'), ('확정', '확정'), ('실주', '실주')], default='예정', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='saleIndustry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='saleType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
