# Generated by Django 2.1.7 on 2020-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_auto_20200221_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='saleIndustry',
            field=models.CharField(blank=True, choices=[('설계', '설계'), ('감리', '감리'), ('학술', '학술'), ('기타', '기타')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='saleType',
            field=models.CharField(blank=True, choices=[('나라장터', '나라장터'), ('기타', '기타')], max_length=100, null=True),
        ),
    ]
