# Generated by Django 2.1.5 on 2019-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventday',
            fields=[
                ('eventDate', models.DateField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=10)),
                ('eventType', models.CharField(choices=[('휴일', '휴일'), ('사내일정', '사내일정')], default='휴일', max_length=10)),
            ],
        ),
    ]
