# Generated by Django 2.1.5 on 2019-03-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventday',
            fields=[
                ('eventDate', models.DateField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=10)),
                ('eventStartDatetime', models.DateTimeField()),
                ('eventEndDatetime', models.DateTimeField()),
            ],
        ),
    ]
