# Generated by Django 2.1.7 on 2020-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='eventType',
            field=models.CharField(choices=[('휴일', '휴일'), ('사내일정', '사내일정'), ('프로젝트일정', '프로젝트일정')], default='휴일', max_length=10),
        ),
    ]
