# Generated by Django 2.1.7 on 2020-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200304_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='eventName',
            field=models.CharField(max_length=200),
        ),
    ]
